version: '3.3'
services:
  frontend:
    container_name: payment_front
    build:
      context: ./front
      dockerfile: Dockerfile
    image: payment_front
    ports:
      - '3000:3000'
    volumes:
      - ./front:/app
  server:
    container_name: payment_api
    build:
      context: ./api
      dockerfile: Dockerfile
    image: payment_api
    ports:
      - '3333:3333'
    volumes:
      - ./api:/app
